### ISSUE TITLE
Help DT

### ISSUE THREAD

**Issue by lopestom** [Fauxly/twrp_device_asus_P#1]
Here's we can write too about.

**Comment by Fauxly** [comment]
оке, какие мои дейсвия перед тем как я запускаю компиляцию? мне нужно скрипты править?

**Comment by lopestom** [comment]
> оке, какие мои дейсвия перед тем как я запускаю компиляцию? мне нужно скрипты править?

First, here all is with english language.

**Comment by lopestom** [comment]
The second,
You not made the modification in the:
# Architecture
"TARGET_ARCH := x86

for
TARGET_ARCH := x86

Has `"` simbol and not need that.

**Comment by lopestom** [comment]
File made with your repository.
https://github.com/lopestom/Action-Recovery-Builder-CT/releases/tag/3863493826

logs: https://github.com/lopestom/Action-Recovery-Builder-CT/commit/2fce90fd6fc8589162660acbd9e05127af5872c6/checks/10501915344/logs


https://github.com/lopestom/Action-Recovery-Builder-CT/actions/runs/3863493826/jobs/6585719772#step:16:1

**Comment by Fauxly** [comment]
Hi, I see you added the changes, I can't compile the recovery

**Comment by lopestom** [comment]
> Hi, I see you added the changes, I can't compile the recovery

I already answered you in 4pda about your questions.

I put in some parts of the original recovery to see if it would work. But really only you can know.
I don't know your intentions in wanting a Custom Recovery for such an old device and I don't want to know. It's your choice.

But since we compiled the first TWRP and I opened the version file, I saw that it was **version 3.7.0_9.** I really don't think it will work on your device because it has a very new structure of Android 9.
What might work is to take the source code from that era of the Android 5 and/or Android 6 version and try something. I think a TWRP3.2 would be ideal.
So I believe it is not worth the time and effort to compile a current TWRP due to several doubts and several changes in the TeamWin source code.
But if you want to keep trying, I reinforce what I wrote before, use your computer with the A5/6 source code or keep trying using Actions with the current source code - your choice.
I'll try to help as much as possible, but with free time and obviously everything can go wrong. But like I said, it's your time and your device.
